### ISSUE TITLE
Map: plot related posts pins

### ISSUE THREAD

**Issue by leogermani** [EarthJournalismNetwork/jeo-plugin#13]

**Comment by leopiccionia** [comment]
I've made some investigations about templates and I think I've made some progress in 0ab0138ece52d27d13bb557375d83b3c7ec0a8b5.

I've decided to use `lodash.template` due to the following reasons:
* It's reasonably small, fast and well-maintained;
* [Its syntax](https://lodash.com/docs/4.17.15#template) is similar to PHP templates and very expressive;
* It runs in the browser without headaches; other contenders were originally built for Node and required workarounds.

I'm passing the templates' contents to front-end, instead of their URLs, to make the script synchronous and more reliable. We can discuss alternatives to `wp_localize_script`, like using `<template/>` or `<script type="x-template/>` tags as templates.

There are still many room for improvements:
* It's currently compiling the template for each iteration of the loop. It can be optimized for caching templates;
* It's not yet extendable, i.e. a plugin user can't yet override default templates or create their own templates (e.g. for layers tooltips). I'm open to suggestions about how to do it;
* We can discuss naming conventions, file extensions and how to document it.

If it's green-lighted, I'll adopt the same strategies for "More info" in maps, layers tooltips, etc.

**Comment by leogermani** [comment]
Nice! Perfect.

As for the improvements, the most important thing is to allow templates to be overwritten by a plugin or theme author. This can be easily done here:

https://github.com/EarthJournalismNetwork/jeo-plugin/blob/0ab0138ece52d27d13bb557375d83b3c7ec0a8b5/src/includes/class-jeo.php#L153

Instead of calling the file directly, we could use a method, something like `get_template($template_name)`. In this method we could do one of the following, or both:

* Pass the response through a filter, so themes and plugins can modify the result and return other templates
* First check if the template exists in a `jeo` folder inside the current theme folder (using [get_template_part](https://developer.wordpress.org/reference/functions/get_template_part/).

I think it's worth to do both.

And yes, documentation is needed. What the templates are, what variables are available inside it.

**Comment by brunosmartin** [comment]
@leopiccionia keeping this open until documentation is done
