### ISSUE TITLE
Map legend, content and related posts pin modal styles

### ISSUE THREAD

**Issue by brunosmartin** [EarthJournalismNetwork/jeo-plugin#35]
all styles here:
Desktop: https://invis.io/UMUH8CZFSD4#/409703218_Desktop_HD_JEO_Post_Legendas
Mobile: https://invis.io/UMUH8CZFSD4#/409843014_Mobile_Portrait_Post_Legendas
- [x] Map content styles 
- [x] legend styles
- [x] posts pin modal styles. The modal must not be above the legend.
- [x]  (bug) if a layer's name breaks in two lines, the checkbox mark will appear outside the box:
![image](https://user-images.githubusercontent.com/12487823/82820076-e6480d80-9e77-11ea-8580-8c2650d70830.png)

fixed for common names:
![image](https://user-images.githubusercontent.com/12487823/82835273-e78a3200-9e99-11ea-9968-0d7c6be82035.png)

fixed for long names:
![image](https://user-images.githubusercontent.com/12487823/82845742-16b19b00-9ebc-11ea-9079-a7bfe7a7ecfb.png)

- [x] Stories pin points' popups don't need to show "Published in". They could simply show date at the first line and title at the second line. Here's an example:

**Comment by isaquemelo** [comment]
I had a talk with the UX expert and we discussed about the best way of showing the circle legend, the need for a  toggle option on desktop for hidding the legend wrapper and about the icons as a whole. The solucion achieved was a little bit different from the one We've got on the layout, but the UX was certainly improved.

**Comment by bwstefano** [comment]
I can't validate this in full because of issue #98. However I've already noticed that if a layer's name breaks in two lines, the checkbox mark will appear outside the box:

![layer_name_two_lines](https://user-images.githubusercontent.com/11841075/82734349-deaa2c80-9cf0-11ea-9ca8-4d55b728723c.png)

This verification can be done at the map at https://jeo.hacklab.com.br/index.php/maps/mapa/

Also could swappable layers appear all together (I mean, one after another without having a switchable layer between them) and with a radio button instead of a checkbox?

**Comment by bwstefano** [comment]
@pamelars86, it seems swappable layers are still not in radio buttons instead of checkboxes. And "published in" is still there. Please review.

**Comment by pamelars86** [comment]
- Published in was removed now
- A new issue (#108) Radio buttons instead of checkbox for swappable layers
