### ISSUE TITLE
in icon legend panel, indicate the minimum size, in pixels, of the icon

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [EarthJournalismNetwork/jeo-plugin#47]
- [x] colocar texto indicativo do tamanho do ícone embaixo do select, antes da lista de ícones.
- [x] substituir a imagem placeholder do http://via.placeholder.com/ por uma no próprio plugin, mais  legível

**Comment by rafaelchavesfreitas** [comment]
acho que a posição do indicador de tamanho não ficou boa (ver print abaixo). não é necessário repetir a mensagem para cada ícone. acho que pode ser um textinho antes dos icones, abaixo do select. vou editar a descrição da issue com os detalhes a corrigir.
![image](https://user-images.githubusercontent.com/1181261/78145977-eee80e80-7407-11ea-845e-6e823078b527.png)

**Comment by hockpond** [comment]
Coloquei um icon do Dashicon que eu achei intuitivo. Se preferir algum outro só avisar que eu modifico

**Comment by bwstefano** [comment]
If we have a minimum size, shouldn't we prevent user to not use an image smaller than it? Otherwise, it should be clear this is a recommended min size.

For this test I edited [this layer](https://jeo.hacklab.com.br/wp-admin/post.php?post=23&action=edit), which is used in [this map](https://jeo.hacklab.com.br/index.php/maps/mapa/).
