### ISSUE TITLE
Admin - Add download source link configuration to layers

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [EarthJournalismNetwork/jeo-plugin#74]
metadata key is `source_url`

related to: #28

**Comment by bwstefano** [comment]
Just a few corrections to how these fields are labeled:

"Map source url download link" -> "Source data download link"
"Map attribution link" -> "Data attribution link"
"Download source" -> "Download from source"

Could we also have a field to add the source's name so it appears to the user with a link instead of having only the URL in front of "Attribution:"? The field would be labeled "Source name".

To give an example, a source that's named "NASA FIRMS" and have a "Data attribution link" set to https://firms.modaps.eosdis.nasa.gov/download/ would be presented like this to visitors in map info:

> Attribution: [NASA FIRMS](https://firms.modaps.eosdis.nasa.gov/download/)

**Comment by icarooliv** [comment]
@bwstefano what do you think about 'Data attribution name' or something like that? 

'Source name' might be confusing once we are referencing this field to 'Data attribution link' not to 'Source data download link'.

**Comment by bwstefano** [comment]
@icarooliv, good idea, makes sense. Let's go with 'Data attribution name', then

**Comment by bwstefano** [comment]
Can't close this one yet as the testing environment isn't reflecting the suggestion above from @icarooliv. Instead of being called as 'Source name', the field should be called 'Data attribution name'.

**Comment by bwstefano** [comment]
Has anything changed here? It doesn't look like, @icarooliv, @rafaelchavesfreitas, @hockpond 👇
![74](https://user-images.githubusercontent.com/11841075/83703366-c20dce80-a5e5-11ea-823b-15b3ac422c91.jpg)

**Comment by pamelars86** [comment]
@bwstefano 
It was changed but is not available in test environment yet. I am going to check it.
